openapi: 3.1.0
info:
  title: Permit.io Access Requests (EAP) Access Requests (EAP) Activity Log API
  description: '

    Authorization as a service

    '
  version: 2.0.0
tags:
- name: Activity Log
paths:
  /v2/activity:
    get:
      tags:
      - Activity Log
      summary: List Activity Events
      description: 'Fetches all API History events for given filters.

        Available to members with Viewer (or higher) role.'
      operationId: list_activity_events
      parameters:
      - description: Actor ID to search
        required: false
        schema:
          items:
            type: string
          type: array
          title: Actor Id
          description: Actor ID to search
        name: actor_id
        in: query
      - description: Actor display name to search
        required: false
        schema:
          type: string
          title: Actor Display Name
          description: Actor display name to search
        name: actor_display_name
        in: query
      - description: Actor type to search (member, user, api_key)
        required: false
        schema:
          items:
            type: string
          type: array
          title: Actor Type
          description: Actor type to search (member, user, api_key)
        name: actor_type
        in: query
      - description: Projects to include in search
        required: false
        schema:
          items:
            type: string
          type: array
          title: Project Id
          description: Projects to include in search
        name: project_id
        in: query
      - description: Environments to include in search
        required: false
        schema:
          items:
            type: string
          type: array
          title: Env Id
          description: Environments to include in search
        name: env_id
        in: query
      - description: Retrieve only events after this timestamp (seconds since epoch)
        required: false
        schema:
          type: integer
          title: Timestamp From
          description: Retrieve only events after this timestamp (seconds since epoch)
        name: timestamp_from
        in: query
      - description: Retrieve only events before this timestamp (seconds since epoch)
        required: false
        schema:
          type: integer
          title: Timestamp Until
          description: Retrieve only events before this timestamp (seconds since epoch)
        name: timestamp_until
        in: query
      - description: Page number of the results to fetch, starting at 1.
        required: false
        schema:
          type: integer
          minimum: 1.0
          title: Page
          description: Page number of the results to fetch, starting at 1.
          default: 1
        name: page
        in: query
      - description: The number of results per page (max 100).
        required: false
        schema:
          type: integer
          maximum: 100.0
          minimum: 1.0
          title: Per Page
          description: The number of results per page (max 100).
          default: 30
        name: per_page
        in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LimitedPaginatedResult_ActivityLogEventRead_'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - HTTPBearer: []
  /v2/activity/types:
    get:
      tags:
      - Activity Log
      summary: List Activity Types
      operationId: list_activity_types
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - HTTPBearer: []
components:
  schemas:
    ActivityDetailsList:
      properties:
        kind:
          type: string
          enum:
          - list
          title: Kind
          default: list
        type:
          type: string
          title: Type
        items:
          items:
            $ref: '#/components/schemas/ActivityDetailsObjectData'
          type: array
          title: Items
      additionalProperties: false
      type: object
      required:
      - type
      - items
      title: ActivityDetailsList
    ActivityDetailsObjectData:
      properties:
        id:
          type: string
          format: uuid
          title: Id
        key:
          type: string
          title: Key
      additionalProperties: false
      type: object
      title: ActivityDetailsObjectData
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    LimitedPaginatedResult_ActivityLogEventRead_:
      properties:
        data:
          items:
            $ref: '#/components/schemas/ActivityLogEventRead'
          type: array
          title: Data
          description: List of Activity Log Events
        total_count:
          type: integer
          minimum: 0.0
          title: Total Count
        page_count:
          type: integer
          minimum: 0.0
          title: Page Count
          default: 0
        pagination_count:
          type: integer
          minimum: 0.0
          title: Pagination Count
      additionalProperties: false
      type: object
      required:
      - data
      - total_count
      - pagination_count
      title: LimitedPaginatedResult[ActivityLogEventRead]
    ActivityLogEventRead:
      properties:
        id:
          type: string
          format: uuid
          title: Id
        timestamp:
          type: string
          format: date-time
          title: Timestamp
        activity_id:
          type: string
          title: Activity Id
        activity_description:
          type: string
          title: Activity Description
        activity_details:
          additionalProperties:
            oneOf:
            - $ref: '#/components/schemas/ActivityDetailsObject'
            - $ref: '#/components/schemas/ActivityDetailsList'
            discriminator:
              propertyName: kind
              mapping:
                object: '#/components/schemas/ActivityDetailsObject'
                list: '#/components/schemas/ActivityDetailsList'
          type: object
          title: Activity Details
        client_ip:
          type: string
          title: Client Ip
        actor_type:
          type: string
          title: Actor Type
        actor_id:
          type: string
          format: uuid
          title: Actor Id
        actor_display_name:
          type: string
          title: Actor Display Name
        org_id:
          type: string
          format: uuid
          title: Org Id
        project_key:
          type: string
          title: Project Key
        project_id:
          type: string
          format: uuid
          title: Project Id
        env_key:
          type: string
          title: Env Key
        env_id:
          type: string
          format: uuid
          title: Env Id
      additionalProperties: false
      type: object
      required:
      - id
      - timestamp
      - client_ip
      - actor_type
      - actor_id
      title: ActivityLogEventRead
    ActivityDetailsObject:
      properties:
        id:
          type: string
          format: uuid
          title: Id
        key:
          type: string
          title: Key
        kind:
          type: string
          enum:
          - object
          title: Kind
          default: object
        type:
          type: string
          title: Type
      additionalProperties: false
      type: object
      required:
      - type
      title: ActivityDetailsObject
  securitySchemes:
    HTTPBearer:
      type: http
      description: 'Authorization header, we support the bearer authentication scheme (see: RFC 6750)'
      scheme: bearer
      bearerFormat: JWT
